imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

parameters:
    locale: en
    default_url: 'http://homoglyphs.net/?lang=en&exc7=1&exc8=1&exc13=1&exc14=1'

framework:
    secret: '%secret%'
    serializer: { enable_annotations: true }
    default_locale: '%locale%'
    fragments: ~
    php_errors:
        log: true
